language: rust

rust:
  - nightly
  - beta
  - stable

cache:
  - apt
  - cargo

matrix:
  include:
    - env: ARCH=i686-unknown-linux-gnu
      os: linux
    - env: ARCH=x86_64-unknown-linux-gnu
      os: linux
    - env: 
        - ARCH=x86_64-unknown-linux-gnu
        - DO_LINT=YES
      os: linux
    - env: ARCH=i686-pc-windows-msvc
      os: windows
    - env: ARCH=x86_64-pc-windows-msvc
      os: windows
    - env: ARCH=x86_64-apple-darwin
      os: osx
    - env: ARCH=i686-apple-darwin
      os: osx

addons:
  apt:
    packages:
      - libasound2-dev
      - libudev-dev
      - pkg-config

before_script:
  - rustup update
  - rustup component add clippy
  - rustup target add $ARCH

script:
  - cargo test --target=$ARCH
  - |
    if [ $DO_LINT == "YES" ]; then
      cargo clippy --all-targets --all-features;
      cargo fmt -- --check
      # -- -D warnings
    fi
